import type { Metadata } from "next";
import "./globals.css";
import NavBar from "@/components/NavBar";
import GlobalFooter from "@/components/GlobalFooter";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es" suppressHydrationWarning>
      <body className="antialiased">
        <NavBar />
        {children}
        <GlobalFooter />
      </body>
    </html>
  );
}
